name: pjs test

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Linting
        run: docker-compose -f ./docker-compose.yml run lint
      - name: Tests
        run: docker-compose -f ./docker-compose.yml run tests
