name: pjs test

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Linting
        run: docker-compose run lint
      - name: Tests
        run: docker-compose run tests
